// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa8syNpWgpCtaUwWiA9gSC84E8nGPaWcY',
    appId: '1:844885772166:web:6c0611c867886dbb17ce07',
    messagingSenderId: '844885772166',
    projectId: 'varuna-ppl',
    authDomain: 'varuna-ppl.firebaseapp.com',
    storageBucket: 'varuna-ppl.appspot.com',
    measurementId: 'G-CK3VSXYYPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBzWf2juQLeoFGsPwqS7Z8nh9oIHXFXQ',
    appId: '1:844885772166:android:cec135e3e42bd5bd17ce07',
    messagingSenderId: '844885772166',
    projectId: 'varuna-ppl',
    storageBucket: 'varuna-ppl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3uP8ZnCv_T3hpIkVmjdM16N9xf9K8ds',
    appId: '1:844885772166:ios:22166dbec3667ae717ce07',
    messagingSenderId: '844885772166',
    projectId: 'varuna-ppl',
    storageBucket: 'varuna-ppl.appspot.com',
    iosClientId: '844885772166-frnc1tnr9iif9qvvqpr0abbvb97h3on7.apps.googleusercontent.com',
    iosBundleId: 'com.example.varuna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV3uP8ZnCv_T3hpIkVmjdM16N9xf9K8ds',
    appId: '1:844885772166:ios:22166dbec3667ae717ce07',
    messagingSenderId: '844885772166',
    projectId: 'varuna-ppl',
    storageBucket: 'varuna-ppl.appspot.com',
    iosClientId: '844885772166-frnc1tnr9iif9qvvqpr0abbvb97h3on7.apps.googleusercontent.com',
    iosBundleId: 'com.example.varuna',
  );
}
